In [1]:
import pandas as pd
import numpy as np

data = np.array([
    [2, 60, "Campus", 48],
    [4, 75, "Online", 60],
    [None, 82, "Campus", 85],
    [7, 105, "Online", 80],
    [5, 80, "Campus", 72]
])

columns = ["Hours", "Attendance", "Mode", "Score"]

df = pd.DataFrame(data=data, columns=columns)
df.head()

  Hours Attendance    Mode Score
0     2         60  Campus    48
1     4         75  Online    60
2  None         82  Campus    85
3     7        105  Online    80
4     5         80  Campus    72

In [3]:
print(f"\nShape: {df.shape}")
print(f"\nMissing Values: {df.isna().sum()}")
print(f"\nOriginal Data: {df}")

Shape: (5, 4)

Missing Values: Hours         1
Attendance    0
Mode          0
Score         0
dtype: int64

Original Data:   Hours Attendance    Mode Score
0     2         60  Campus    48
1     4         75  Online    60
2  None         82  Campus    85
3     7        105  Online    80
4     5         80  Campus    72

In [4]:
df.to_csv("students.csv", index=False)

In [5]:
loaded = pd.read_csv("students.csv")
loaded

   Hours  Attendance    Mode  Score
0    2.0          60  Campus     48
1    4.0          75  Online     60
2    NaN          82  Campus     85
3    7.0         105  Online     80
4    5.0          80  Campus     72